// Bộ đề ảnh Writing Q1-5 — sinh tự động bởi scripts/gen-q15-bank.mjs, KHÔNG sửa tay.
//
// Ảnh nguồn do giáo viên cung cấp, đã chuẩn hoá bởi scripts/normalize-q15-images.mjs
// (map tên gốc: scripts/writing-q1-5-source-map.json).
//
// Phân loại độ khó (ảnh gate mức, cặp từ khớp mức):
//   easy   — ảnh 1 chủ thể + 1 hành động rõ  → cặp từ danh từ + động từ hành động
//   medium — 2-3 chủ thể / có quan hệ vị trí  → cặp từ danh từ + giới từ
//   hard   — cảnh đông, 2 hành động song song, hoặc trọng tâm là vật thể
//            → cặp từ có liên từ (while/because) hoặc động từ buộc dùng bị động
//
// Phân bố: 30 hard · 28 medium · 21 easy

import type { WritingQ15Exercise } from "./writing-q1-5";

export const WRITING_Q1_5_BANK: WritingQ15Exercise[] = [
  {
    id: "q15-001",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-001.jpg",
    imageAlt: "Một cây lớn đổ chắn ngang con đường nhựa giữa rừng.",
    keywords: ["tree", "block"],
    modelAnswers: ["The road is blocked by a fallen tree.", "A large tree has fallen and is blocking the road."],
    tip: "Không có người trong ảnh → dùng bị động: is blocked by. Trọng tâm là con đường bị chắn.",
  },
  {
    id: "q15-002",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-002.jpg",
    imageAlt: "Một nữ nhân viên an ninh sân bay đang kiểm tra một người đàn ông giơ tay ngang.",
    keywords: ["officer", "beside"],
    modelAnswers: ["A security officer is standing beside a man at the checkpoint.", "The officer is checking the passenger beside her."],
    tip: "beside = bên cạnh. Đặt beside ngay trước danh từ chỉ người/vật ở cạnh.",
  },
  {
    id: "q15-003",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-003.jpg",
    imageAlt: "Một người đàn ông đứng thuyết trình trước bảng trắng, hai đồng nghiệp ngồi nghe với laptop.",
    keywords: ["present", "while"],
    modelAnswers: ["While the man is presenting, his colleagues are taking notes.", "A man is presenting his ideas while two colleagues listen."],
    tip: "while nối hai hành động xảy ra cùng lúc → cần 2 mệnh đề, mỗi mệnh đề đủ S + V.",
  },
  {
    id: "q15-004",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-004.jpg",
    imageAlt: "Hai nữ lễ tân sau quầy khách sạn: một người nói điện thoại, một người đưa thẻ cho khách.",
    keywords: ["hand", "while"],
    modelAnswers: ["One receptionist is handing a card to a guest while the other is talking on the phone.", "While one woman answers the phone, her colleague hands a key card to a customer."],
    tip: "Hai người làm hai việc khác nhau → dùng while. Chú ý \"hand something to somebody\".",
  },
  {
    id: "q15-005",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-005.jpg",
    imageAlt: "Phòng khách hiện đại với sofa xám, bàn cà phê kính và bình hoa ở giữa.",
    keywords: ["flowers", "place"],
    modelAnswers: ["A vase of flowers is placed on the coffee table.", "Some flowers are placed on the table in the living room."],
    tip: "Không rõ ai đặt hoa → bị động: is/are placed. Nhớ chia số theo chủ ngữ (vase = số ít, flowers = số nhiều).",
  },
  {
    id: "q15-006",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-006.jpg",
    imageAlt: "Một người đàn ông mặc vest ngồi tại bàn làm việc, dùng laptop.",
    keywords: ["man", "use"],
    modelAnswers: ["The man is using a laptop.", "A man in a suit is using his computer at a desk."],
    tip: "Một người, một hành động rõ ràng → hiện tại tiếp diễn: is + V-ing.",
  },
  {
    id: "q15-007",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-007.jpg",
    imageAlt: "Một người phụ nữ và một người đàn ông đứng đối diện nhau nói chuyện trên nền trắng.",
    keywords: ["man", "to"],
    modelAnswers: ["The man is talking to the woman.", "A man is speaking to a woman while they stand facing each other."],
    tip: "talk/speak + to + người nghe. Không dùng \"talk with somebody about\" ở đây vì chỉ cần 1 câu ngắn.",
  },
  {
    id: "q15-008",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-008.jpg",
    imageAlt: "Một cầu thủ áo đỏ đang sút bóng trên sân vận động.",
    keywords: ["player", "kick"],
    modelAnswers: ["The player is kicking the ball.", "A soccer player is kicking a ball in the stadium."],
    tip: "kick đi thẳng với tân ngữ: kick the ball (không cần giới từ).",
  },
  {
    id: "q15-009",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-009.jpg",
    imageAlt: "Một nữ phục vụ mặc tạp dề kẻ đang bưng khay có bốn tách cà phê trong quán.",
    keywords: ["tray", "with"],
    modelAnswers: ["A waitress is carrying a tray with four cups of coffee.", "The woman is holding a tray with several drinks on it."],
    tip: "with = có/kèm theo, dùng để mô tả vật đi cùng: a tray with cups.",
  },
  {
    id: "q15-010",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-010.jpg",
    imageAlt: "Một người phụ nữ áo tím chạy bộ cùng con chó golden trên đường khu dân cư.",
    keywords: ["dog", "along"],
    modelAnswers: ["A woman is jogging along the street with her dog.", "The woman is walking her dog along the road."],
    tip: "along = dọc theo (đường, bờ sông). Khác on the street (ở trên đường).",
  },
  {
    id: "q15-011",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-011.jpg",
    imageAlt: "Một người đàn ông mặc suit thuyết trình cạnh bảng giấy, nhóm đồng nghiệp ngồi quanh bàn nghe.",
    keywords: ["listen", "while"],
    modelAnswers: ["The employees are listening while their manager gives a presentation.", "While the man is speaking, everyone at the table is listening to him."],
    tip: "listen phải có to khi có tân ngữ: listen to him. Không tân ngữ thì dùng trơn: are listening.",
  },
  {
    id: "q15-012",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-012.jpg",
    imageAlt: "Một người phụ nữ đang thuyết trình trước nhóm nhân viên ngồi nghe trong văn phòng tường gạch.",
    keywords: ["presentation", "give"],
    modelAnswers: ["A presentation is being given to a group of employees.", "A presentation is being given in the office by a woman."],
    tip: "Bị động tiếp diễn: is being + V3 — nhấn mạnh buổi thuyết trình đang diễn ra, không nhấn ai nói.",
  },
  {
    id: "q15-013",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-013.jpg",
    imageAlt: "Một người đàn ông đội mũ bảo hiểm, mang balô, đang đẩy xe đạp qua đường.",
    keywords: ["bicycle", "across"],
    modelAnswers: ["A man is pushing his bicycle across the street.", "The man with a backpack is walking his bicycle across the road."],
    tip: "across = băng qua (từ bên này sang bên kia). So sánh: along = dọc theo.",
  },
  {
    id: "q15-014",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-014.jpg",
    imageAlt: "Sạp trái cây trong cửa hàng: một nữ khách trao tiền cho người bán qua quầy đầy trái cây.",
    keywords: ["fruit", "display"],
    modelAnswers: ["Fresh fruit is displayed at the market stall.", "A lot of fruit is displayed on the counter of the shop."],
    tip: "fruit là danh từ không đếm được → is displayed (số ít). Bị động vì không nhấn ai trưng bày.",
  },
  {
    id: "q15-015",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-015.jpg",
    imageAlt: "Nhiều xe taxi đen kiểu London đậu sát nhau trên phố, một người đứng giữa các xe.",
    keywords: ["taxis", "park"],
    modelAnswers: ["Several taxis are parked along the street.", "Some black taxis are parked next to each other on the road."],
    tip: "Xe đứng yên → bị động trạng thái: are parked. Nếu đang được đỗ thì mới dùng are being parked.",
  },
  {
    id: "q15-016",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-016.jpg",
    imageAlt: "Nhìn từ trên cao: một đám đông người đứng chờ trong sảnh lớn có sàn gạch ô vuông.",
    keywords: ["crowd", "gather"],
    modelAnswers: ["A large crowd is gathered in the lobby.", "A crowd of people is gathered inside the hall."],
    tip: "crowd là danh từ tập hợp, chia số ít: a crowd is. \"is gathered\" mô tả trạng thái đã tụ lại.",
  },
  {
    id: "q15-017",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-017.jpg",
    imageAlt: "Một người đàn ông đội mũ nồi, mặc áo khoác đen, dắt con chó đen đi trên tuyết.",
    keywords: ["dog", "through"],
    modelAnswers: ["A man is walking his dog through the snow.", "The man is taking his dog for a walk through the snow."],
    tip: "through = xuyên qua/băng qua bên trong một khối (snow, forest, crowd). Khác across (qua bề mặt phẳng).",
  },
  {
    id: "q15-018",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-018.jpg",
    imageAlt: "Một người đàn ông bê thùng carton lớn đi trên tấm ván dốc lên xe tải thùng.",
    keywords: ["box", "into"],
    modelAnswers: ["A man is carrying a box into the truck.", "The worker is loading a box into a moving truck."],
    tip: "into = vào bên trong (có chuyển động). Nếu đã ở trong rồi thì dùng in the truck.",
  },
  {
    id: "q15-019",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-019.jpg",
    imageAlt: "Ảnh đen trắng cầu Brooklyn: lối đi bộ giữa các dây văng và trụ đá, vài người đi bộ phía xa.",
    keywords: ["bridge", "support"],
    modelAnswers: ["The bridge is supported by steel cables.", "The bridge is supported by thick cables and stone towers."],
    tip: "Bị động + by để nêu tác nhân: is supported by + vật. Đây là dạng câu tả kết cấu rất hay gặp.",
  },
  {
    id: "q15-020",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-020.jpg",
    imageAlt: "Ba người ngồi ngoài trời, hai người phụ nữ cùng đọc một tờ giấy, người đàn ông đứng nhìn theo.",
    keywords: ["read", "while"],
    modelAnswers: ["Two women are reading a document while a man watches over their shoulders.", "While the women are reading a letter, the man is looking at it too."],
    tip: "Mệnh đề sau while có thể dùng hiện tại đơn hoặc tiếp diễn; tiếp diễn tự nhiên hơn khi tả ảnh.",
  },
  {
    id: "q15-021",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-021.jpg",
    imageAlt: "Một người phụ nữ ngồi thử giày trong cửa hàng, phía sau là kệ giày.",
    keywords: ["shoes", "in"],
    modelAnswers: ["The woman is trying on shoes in a shoe store.", "A woman is putting on a pair of shoes in the store."],
    tip: "in + không gian bên trong (store, room). Chú ý phrasal verb try on / put on.",
  },
  {
    id: "q15-022",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-022.jpg",
    imageAlt: "Một người đàn ông áo polo kẻ đứng trong bếp, đang cắt đồ ăn trên mặt bếp.",
    keywords: ["man", "cut"],
    modelAnswers: ["The man is cutting some food in the kitchen.", "A man is cutting vegetables on the kitchen counter."],
    tip: "Một người một hành động → is + V-ing. cut đi thẳng với tân ngữ.",
  },
  {
    id: "q15-023",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-023.jpg",
    imageAlt: "Một phụ nữ mặc suit chỉ vào biểu đồ trên bảng giấy, hai người ngồi nghe.",
    keywords: ["chart", "at"],
    modelAnswers: ["The woman is pointing at a chart.", "A woman is pointing at the chart during a meeting."],
    tip: "point at/to + vật được chỉ. Không nói \"point the chart\".",
  },
  {
    id: "q15-024",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-024.jpg",
    imageAlt: "Một gia đình bốn người ở bờ biển: hai đứa trẻ được cha mẹ cho ngồi trên vai.",
    keywords: ["children", "carry"],
    modelAnswers: ["The children are being carried on their parents' shoulders.", "Two children are being carried on the shoulders of their parents."],
    tip: "Bị động tiếp diễn: are being + V3. Dùng khi muốn lấy \"children\" làm chủ ngữ.",
  },
  {
    id: "q15-025",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-025.jpg",
    imageAlt: "Một người mang balô đang bước lên xe bus, người khác cầm túi đi phía sau.",
    keywords: ["bus", "onto"],
    modelAnswers: ["A passenger is getting onto the bus.", "The man with a backpack is stepping onto the bus."],
    tip: "onto = lên trên (có chuyển động). get onto / step onto the bus.",
  },
  {
    id: "q15-026",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-026.jpg",
    imageAlt: "Hai người đi bộ trong bão tuyết, hàng xe đậu hai bên phủ đầy tuyết.",
    keywords: ["cars", "cover"],
    modelAnswers: ["The cars are covered with snow.", "All the parked cars are covered with thick snow."],
    tip: "be covered with/in + vật phủ lên. Đây là bị động trạng thái, không phải hành động.",
  },
  {
    id: "q15-027",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-027.jpg",
    imageAlt: "Một cô gái đội mũ lưỡi trai, mặc áo khoác, đang đi trên tuyết.",
    keywords: ["girl", "walk"],
    modelAnswers: ["The girl is walking in the snow.", "A girl in a jacket is walking across the snow."],
    tip: "walk không cần tân ngữ. Thêm in the snow để nêu bối cảnh.",
  },
  {
    id: "q15-028",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-028.jpg",
    imageAlt: "Hai người đứng chờ ở nhà chờ xe bus, một người có vali kéo bên cạnh.",
    keywords: ["suitcase", "next to"],
    modelAnswers: ["A woman is standing next to her suitcase.", "The woman is waiting next to a suitcase at the bus station."],
    tip: "next to = ngay bên cạnh. Cả cụm next to là một giới từ, không tách rời.",
  },
  {
    id: "q15-029",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-029.jpg",
    imageAlt: "Bốn đứa trẻ chơi ở sân sau, một đứa đẩy xe rùa trên cỏ, hàng rào gỗ phía sau.",
    keywords: ["push", "while"],
    modelAnswers: ["One child is pushing a wheelbarrow while the others are playing nearby.", "While one girl pushes a wheelbarrow, the other children are playing in the yard."],
    tip: "Nhiều người làm việc khác nhau → while. Dùng the others cho những người còn lại.",
  },
  {
    id: "q15-030",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-030.jpg",
    imageAlt: "Một người đàn ông lớn tuổi đeo kính vừa nói điện thoại vừa ghi chép, có laptop trên bàn.",
    keywords: ["write", "while"],
    modelAnswers: ["The man is writing notes while he is talking on the phone.", "While talking on the phone, the man is writing something down."],
    tip: "Một người làm hai việc cùng lúc → while. Có thể rút gọn: while talking on the phone.",
  },
  {
    id: "q15-031",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-031.jpg",
    imageAlt: "Một ông cụ đội mũ ngồi trên ghế băng công viên đọc báo, gậy dựa bên cạnh.",
    keywords: ["man", "read"],
    modelAnswers: ["The man is reading a newspaper.", "An old man is reading a newspaper on a park bench."],
    tip: "read a newspaper / a book — nhớ mạo từ a trước danh từ số ít.",
  },
  {
    id: "q15-032",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-032.jpg",
    imageAlt: "Hàng cây cọ nghiêng rạp trong gió mạnh, trời xám xịt.",
    keywords: ["trees", "blow"],
    modelAnswers: ["The trees are being blown by strong wind.", "The palm trees are being blown around by the wind."],
    tip: "Không có người → bị động. blow (thổi) ở bị động: are being blown by the wind.",
  },
  {
    id: "q15-033",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-033.jpg",
    imageAlt: "Một người đàn ông áo khoác đen nói điện thoại trên phố, phía sau có người đi bộ.",
    keywords: ["phone", "on"],
    modelAnswers: ["The man is talking on the phone.", "A man is speaking on the phone while walking outside."],
    tip: "Cụm cố định: talk/speak ON the phone (không dùng \"in the phone\").",
  },
  {
    id: "q15-034",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-034.jpg",
    imageAlt: "Năm người ngồi quanh bàn ăn tròn có nhiều đĩa thức ăn, ly và hoa ở giữa.",
    keywords: ["table", "set"],
    modelAnswers: ["The table is set for a meal.", "The round table is set with plates, glasses and flowers."],
    tip: "set là động từ bất quy tắc set-set-set → is set. Cụm \"set the table\" = dọn bàn ăn.",
  },
  {
    id: "q15-035",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-035.jpg",
    imageAlt: "Nhiều người đang bước lên tàu điện qua cửa mở, một số người khác đứng chờ phía sau.",
    keywords: ["passengers", "while"],
    modelAnswers: ["Some passengers are getting on the train while others are waiting behind them.", "While some passengers board the train, others are standing in line."],
    tip: "some ... while others ... là cấu trúc rất hay dùng khi ảnh có nhiều người làm việc khác nhau.",
  },
  {
    id: "q15-036",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-036.jpg",
    imageAlt: "Cận cảnh một người đàn ông quỳ xuống sửa bánh sau xe đạp trên đường đá.",
    keywords: ["man", "repair"],
    modelAnswers: ["The man is repairing his bicycle.", "A man is fixing the wheel of his bike."],
    tip: "repair = fix. Cả hai đi thẳng với tân ngữ: repair the bicycle.",
  },
  {
    id: "q15-037",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-037.jpg",
    imageAlt: "Sảnh sân bay: nhiều khách đứng quanh băng chuyền hành lý, có vali và xe đẩy.",
    keywords: ["wait", "because"],
    modelAnswers: ["The passengers are standing around the belt because they are waiting for their luggage.", "People are waiting near the carousel because their bags have not arrived yet."],
    tip: "because nêu lý do → mệnh đề sau phải đủ S + V. wait FOR something.",
  },
  {
    id: "q15-038",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-038.jpg",
    imageAlt: "Một hàng dài người xếp hàng dọc bức tường trên phố, nhiều người đang xem điện thoại.",
    keywords: ["line", "while"],
    modelAnswers: ["People are standing in line while they check their phones.", "Many people are waiting in line while looking at their mobile phones."],
    tip: "stand/wait IN LINE = xếp hàng. Mệnh đề while có thể rút gọn thành while + V-ing.",
  },
  {
    id: "q15-039",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-039.jpg",
    imageAlt: "Toàn cảnh bãi biển thành phố: cao ốc ven biển, bãi cát đông người, thuyền buồm trên biển xanh.",
    keywords: ["beach", "crowd"],
    modelAnswers: ["The beach is crowded with tourists.", "The beach is crowded with people on a sunny day."],
    tip: "be crowded with + người/vật = đông nghẹt. Đây là tính từ dạng V3, dùng như bị động.",
  },
  {
    id: "q15-040",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-040.jpg",
    imageAlt: "Hai người đàn ông lớn tuổi ngồi đối diện chơi cờ trên chiếc bàn ngoài trời.",
    keywords: ["board", "between"],
    modelAnswers: ["A chessboard is on the table between two men.", "The chess board is between the two players."],
    tip: "between = giữa hai đối tượng. Nếu từ ba đối tượng trở lên thì dùng among.",
  },
  {
    id: "q15-041",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-041.jpg",
    imageAlt: "Sáu người bạn ngồi quanh bàn ăn trong bếp, trên bàn có đồ ăn, bình nước và hoa.",
    keywords: ["chat", "while"],
    modelAnswers: ["A group of friends are chatting while they have lunch together.", "While they are eating, the friends are chatting around the table."],
    tip: "chat = trò chuyện thân mật. Với \"a group of friends\" có thể chia are (nhấn từng người) hoặc is (nhấn cả nhóm).",
  },
  {
    id: "q15-042",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-042.jpg",
    imageAlt: "Một phụ nữ ngồi ở bàn văn phòng, vừa nghe điện thoại cố định vừa ghi chép.",
    keywords: ["message", "because"],
    modelAnswers: ["She is writing down a message while she is on the phone.", "The woman is taking a message while she talks to a customer on the phone."],
    tip: "write down / take a message = ghi lại lời nhắn. \"be on the phone\" = đang nói điện thoại.",
  },
  {
    id: "q15-043",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-043.jpg",
    imageAlt: "Một người đàn ông đang bê thùng carton lớn, nền tường trơn.",
    keywords: ["man", "carry"],
    modelAnswers: ["The man is carrying a box.", "A man is carrying a large cardboard box."],
    tip: "carry = bê/mang đi. Nền ảnh trống nên chỉ cần câu ngắn: S + is carrying + O.",
  },
  {
    id: "q15-044",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-044.jpg",
    imageAlt: "Một người thợ may đeo thước dây quanh cổ ngồi làm việc tại máy may trong xưởng.",
    keywords: ["tailor", "sew"],
    modelAnswers: ["The tailor is sewing at a sewing machine.", "A tailor is sewing a piece of cloth."],
    tip: "sew /səʊ/ = may vá. Có thể dùng không tân ngữ (is sewing) hoặc có tân ngữ (is sewing a shirt).",
  },
  {
    id: "q15-045",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-045.jpg",
    imageAlt: "Hai người đàn ông mặc suit ngồi ở bàn họp, một người cầm tập tài liệu và đang nói.",
    keywords: ["papers", "over"],
    modelAnswers: ["The two men are looking over some papers.", "One man is going over the papers with his colleague."],
    tip: "look over / go over = xem lại, rà soát. over ở đây là một phần của phrasal verb.",
  },
  {
    id: "q15-046",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-046.jpg",
    imageAlt: "Nhiều thuyền cao tốc sơn xanh đỏ đậu san sát dọc cầu cảng.",
    keywords: ["boats", "tie"],
    modelAnswers: ["The boats are tied to the dock.", "Many speedboats are tied up along the pier."],
    tip: "be tied to = được buộc vào. Bị động trạng thái vì thuyền đang ở trạng thái đã buộc.",
  },
  {
    id: "q15-047",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-047.jpg",
    imageAlt: "Một cầu thủ đang sút bóng trên sân vận động về đêm dưới ánh đèn.",
    keywords: ["player", "shoot"],
    modelAnswers: ["The player is shooting the ball.", "A soccer player is shooting the ball toward the goal."],
    tip: "shoot = sút (về phía cầu môn). shoot-shot-shot, V-ing là shooting.",
  },
  {
    id: "q15-048",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-048.jpg",
    imageAlt: "Một đôi nam nữ ngồi trong xe hơi cùng xem tấm bản đồ giấy, người đàn ông ở ghế lái.",
    keywords: ["map", "inside"],
    modelAnswers: ["A couple is looking at a map inside a car.", "The two people are reading a map inside the car."],
    tip: "inside = bên trong (nhấn mạnh hơn in). Dùng khi muốn làm rõ không gian kín.",
  },
  {
    id: "q15-049",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-049.jpg",
    imageAlt: "Bốn người phụ nữ ngồi quanh chiếc bàn trắng trong văn phòng, có cốc cà phê và sổ tay.",
    keywords: ["women", "around"],
    modelAnswers: ["Four women are sitting around a table.", "Some women are sitting around a small table in the office."],
    tip: "around = xung quanh (bao quanh một vật). Rất hay dùng: sit around a table.",
  },
  {
    id: "q15-050",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-050.jpg",
    imageAlt: "Một chiếc thuyền gỗ nhỏ sơn đỏ nổi một mình trên mặt nước xanh.",
    keywords: ["boat", "float"],
    modelAnswers: ["The boat is floating on the water.", "A small red boat is floating on the water."],
    tip: "float = nổi. Không có người trong ảnh nhưng vẫn dùng chủ động vì thuyền tự nổi.",
  },
  {
    id: "q15-051",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-051.jpg",
    imageAlt: "Một đầu bếp mặc đồng phục trắng đang rót dầu vào chảo đồ ăn trong bếp nhà hàng.",
    keywords: ["chef", "pour"],
    modelAnswers: ["The chef is pouring oil into the pan.", "A chef is pouring something into a frying pan."],
    tip: "pour = rót/đổ. Thường đi với into (vào trong) hoặc onto (lên trên).",
  },
  {
    id: "q15-052",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-052.jpg",
    imageAlt: "Một ông cụ ngồi trên ghế băng gỗ trong công viên lúc chiều, cây gậy dựa bên cạnh.",
    keywords: ["bench", "on"],
    modelAnswers: ["The man is sitting on a wooden bench in the park.", "An old man is resting on a bench with his cane beside him."],
    tip: "sit ON a bench/chair (bề mặt để ngồi), nhưng sit IN an armchair (ghế bọc, lún vào).",
  },
  {
    id: "q15-053",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-053.jpg",
    imageAlt: "Một phụ nữ áo vàng cầm dù và điện thoại, đi trên quảng trường ướt mưa.",
    keywords: ["umbrella", "under"],
    modelAnswers: ["The woman is walking under an umbrella.", "A woman is holding a phone while walking under her umbrella."],
    tip: "under = bên dưới. Chú ý: đi dưới dù nói under an umbrella, không nói \"in an umbrella\".",
  },
  {
    id: "q15-054",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-054.jpg",
    imageAlt: "Những cây cọ nghiêng rạp trong cơn bão, mây đen phủ kín trời.",
    keywords: ["trees", "bend"],
    modelAnswers: ["The palm trees are bent by the strong wind.", "The trees are being bent by the wind during the storm."],
    tip: "bend-bent-bent. are bent (trạng thái nghiêng) khác are being bent (đang bị làm nghiêng).",
  },
  {
    id: "q15-055",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-055.jpg",
    imageAlt: "Tủ quần áo mở hai cánh, nhiều áo treo trên móc, quần gấp xếp dưới.",
    keywords: ["clothes", "hang"],
    modelAnswers: ["The clothes are hung on hangers in the closet.", "Some clothes are hung inside the wardrobe."],
    tip: "hang-hung-hung (treo đồ). Đừng lẫn với hang-hanged-hanged (treo cổ).",
  },
  {
    id: "q15-056",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-056.jpg",
    imageAlt: "Một phụ nữ ngồi trong bếp đang ăn đĩa mì spaghetti bằng nĩa.",
    keywords: ["woman", "eat"],
    modelAnswers: ["The woman is eating pasta.", "A woman is eating a plate of spaghetti in the kitchen."],
    tip: "eat + món ăn. Không cần giới từ: eat pasta (không nói \"eat of pasta\").",
  },
  {
    id: "q15-057",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-057.jpg",
    imageAlt: "Một phụ nữ ngồi trên ghế đẩu trong cửa hàng giày, nhiều đôi giày đặt dưới sàn trước mặt.",
    keywords: ["shoes", "in front of"],
    modelAnswers: ["Several pairs of shoes are in front of the woman.", "There are some shoes in front of her on the floor."],
    tip: "in front of = phía trước (bên ngoài). Khác in the front of = ở phần phía trước bên trong.",
  },
  {
    id: "q15-058",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-058.jpg",
    imageAlt: "Một người đàn ông râu bạc nói vào điện thoại rồi ghi chép vào sổ, có laptop trên bàn.",
    keywords: ["record", "while"],
    modelAnswers: ["He is recording a voice message while writing in his notebook.", "The man is recording a message while he takes notes."],
    tip: "Rút gọn mệnh đề while: while + V-ing khi hai mệnh đề cùng chủ ngữ.",
  },
  {
    id: "q15-059",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-059.jpg",
    imageAlt: "Em bé sơ sinh nằm ngủ trong cot trắng, bên cạnh có hai con thỏ bông.",
    keywords: ["baby", "sleep"],
    modelAnswers: ["The baby is sleeping in a crib.", "A baby is sleeping next to two stuffed rabbits."],
    tip: "sleep là động từ chỉ trạng thái nhưng vẫn dùng tiếp diễn khi tả ảnh: is sleeping.",
  },
  {
    id: "q15-060",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-060.jpg",
    imageAlt: "Lớp học với nhiều học sinh ngồi ở bàn viết bài, sách vở mở trước mặt.",
    keywords: ["desks", "at"],
    modelAnswers: ["The students are writing at their desks.", "Some students are studying at their desks in a classroom."],
    tip: "at + điểm/vị trí cụ thể: at a desk, at a table, at the door.",
  },
  {
    id: "q15-061",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-061.jpg",
    imageAlt: "Một con chim ức đỏ đậu trên cành cây và đang hót, mỏ mở rộng.",
    keywords: ["bird", "sing"],
    modelAnswers: ["The bird is singing on a branch.", "A small bird is singing in a tree."],
    tip: "sing không cần tân ngữ. Thêm on a branch / in a tree để nêu vị trí.",
  },
  {
    id: "q15-062",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-062.jpg",
    imageAlt: "Một con mèo vàng nằm ngủ trên chiếc sofa xám có nhiều gối tựa.",
    keywords: ["cat", "lie"],
    modelAnswers: ["The cat is lying on the sofa.", "An orange cat is lying on a grey couch."],
    tip: "lie (nằm) → V-ing là lying, không phải \"lieing\". Đừng lẫn với lay (đặt xuống).",
  },
  {
    id: "q15-063",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-063.jpg",
    imageAlt: "Một bé trai mặc áo khoác kẻ đang khóc ở sân chơi, cầu trượt đỏ phía sau.",
    keywords: ["boy", "cry"],
    modelAnswers: ["The boy is crying at the playground.", "A little boy is crying in the sandbox."],
    tip: "cry = khóc, không cần tân ngữ. at the playground = ở khu sân chơi.",
  },
  {
    id: "q15-064",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-064.jpg",
    imageAlt: "Một bé gái mặc váy ballet tím đang múa trên sân khấu dưới ánh đèn màu.",
    keywords: ["girl", "dance"],
    modelAnswers: ["The girl is dancing on stage.", "A young ballerina is dancing on the stage."],
    tip: "on stage (không mạo từ) = đang biểu diễn; on the stage = ở trên bục sân khấu.",
  },
  {
    id: "q15-065",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-065.jpg",
    imageAlt: "Một đầu bếp đội mũ trắng đang xào chảo có lửa bùng cao trong bếp nhà hàng.",
    keywords: ["flames", "from"],
    modelAnswers: ["Flames are coming from the frying pan.", "Flames are rising from the pan as the chef cooks."],
    tip: "from = từ (nguồn phát ra). come/rise from + nơi bắt nguồn.",
  },
  {
    id: "q15-066",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-066.jpg",
    imageAlt: "Hai đứa trẻ ngồi ở bàn gỗ trong thư viện, mỗi em đọc một quyển sách.",
    keywords: ["library", "in"],
    modelAnswers: ["The children are reading in the library.", "Two kids are reading books in a library."],
    tip: "in the library / in the classroom — dùng in với không gian có ranh giới.",
  },
  {
    id: "q15-067",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-067.jpg",
    imageAlt: "Một người đàn ông trẻ mặc blazer đang lái chiếc xe hơi đỏ, tay đặt trên vô lăng.",
    keywords: ["man", "drive"],
    modelAnswers: ["The man is driving a car.", "A young man is driving a red car."],
    tip: "drive a car / a bus / a truck. Không dùng \"drive by car\" khi tả người đang lái.",
  },
  {
    id: "q15-068",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-068.jpg",
    imageAlt: "Một phụ nữ áo vàng đội tai nghe, vừa xem laptop vừa ghi chép trong quán cà phê.",
    keywords: ["headphones", "because"],
    modelAnswers: ["She is wearing headphones because she is listening to an online lesson.", "The woman is wearing headphones because she is studying with a video."],
    tip: "because + mệnh đề (S + V). Đừng dùng \"because of\" ở đây vì sau đó phải là danh từ.",
  },
  {
    id: "q15-069",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-069.jpg",
    imageAlt: "Một bé trai đeo kính bơi đang tập bơi với phao ván trong hồ bơi.",
    keywords: ["boy", "swim"],
    modelAnswers: ["The boy is swimming in the pool.", "A boy is swimming with a kickboard in a swimming pool."],
    tip: "swim-swam-swum, V-ing là swimming (gấp đôi m).",
  },
  {
    id: "q15-070",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-070.jpg",
    imageAlt: "Một phụ nữ ngồi bệt trên sàn gỗ, cầm bảng màu và vẽ lên tấm canvas lớn.",
    keywords: ["woman", "paint"],
    modelAnswers: ["The woman is painting a picture.", "A woman is painting on a large canvas."],
    tip: "paint a picture (vẽ tranh) / paint the wall (sơn tường) — cùng một động từ.",
  },
  {
    id: "q15-071",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-071.jpg",
    imageAlt: "Một nữ điều dưỡng áo xanh đỡ ông cụ đang ngồi trên sofa đứng lên, xe lăn bên cạnh.",
    keywords: ["arm", "by"],
    modelAnswers: ["The nurse is holding the old man by the arm.", "A nurse is helping the patient by holding his arm."],
    tip: "Cấu trúc: hold/take somebody BY the arm/hand — dùng the, không dùng his/her.",
  },
  {
    id: "q15-072",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-072.jpg",
    imageAlt: "Một con mèo trắng đen ngồi dưới gầm chiếc ghế gỗ trên sàn gạch có nắng.",
    keywords: ["chair", "under"],
    modelAnswers: ["The cat is sitting under a chair.", "A cat is resting under the wooden chair."],
    tip: "under = ngay bên dưới. Nếu chỉ thấp hơn nhưng không che phủ thì dùng below.",
  },
  {
    id: "q15-073",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-073.jpg",
    imageAlt: "Một đôi nam nữ cùng nâng thùng carton lớn trong nhà khi đang chuyển đồ.",
    keywords: ["box", "between"],
    modelAnswers: ["They are carrying a box between them.", "A man and a woman are lifting a box between them."],
    tip: "carry something between them = hai người cùng bê. Rất hay gặp khi tả hai người khiêng đồ.",
  },
  {
    id: "q15-074",
    difficulty: "easy",
    imageUrl: "/images/skills/writing-q1-5/q15-074.jpg",
    imageAlt: "Một nữ lễ tân mặc suit xám ngồi tại quầy, đang nghe điện thoại cố định.",
    keywords: ["receptionist", "answer"],
    modelAnswers: ["The receptionist is answering the phone.", "A receptionist is answering a call at the front desk."],
    tip: "answer the phone = nghe/trả lời điện thoại. Không cần giới từ sau answer.",
  },
  {
    id: "q15-075",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-075.jpg",
    imageAlt: "Một phụ nữ đẩy xe đẩy hàng đi giữa hai kệ đầy sản phẩm trong siêu thị.",
    keywords: ["cart", "down"],
    modelAnswers: ["The woman is pushing a cart down the aisle.", "A woman is pushing a shopping cart down the supermarket aisle."],
    tip: "down the aisle / down the street = đi dọc theo. Không có nghĩa \"xuống dưới\".",
  },
  {
    id: "q15-076",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-076.jpg",
    imageAlt: "Một người đàn ông đứng giơ tờ biểu đồ trình bày trước nhóm bảy người ngồi quanh bàn họp.",
    keywords: ["chart", "show"],
    modelAnswers: ["A chart is being shown to the team.", "A chart is being shown to the employees during a meeting."],
    tip: "Bị động tiếp diễn: is being shown. show something TO somebody.",
  },
  {
    id: "q15-077",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-077.jpg",
    imageAlt: "Một đôi nam nữ ngồi sát nhau trong nhà hàng cùng xem tấm menu.",
    keywords: ["menu", "at"],
    modelAnswers: ["A couple is looking at a menu in a restaurant.", "Two customers are looking at the menu together."],
    tip: "look at + vật được nhìn. Nhớ at, không nói \"look the menu\".",
  },
  {
    id: "q15-078",
    difficulty: "hard",
    imageUrl: "/images/skills/writing-q1-5/q15-078.jpg",
    imageAlt: "Một người đàn ông mặc blazer trong quán cà phê, một tay cầm tách cà phê, tay kia gõ laptop.",
    keywords: ["coffee", "while"],
    modelAnswers: ["He is drinking coffee while working on his laptop.", "The man is having a cup of coffee while he types on his computer."],
    tip: "Hai hành động cùng chủ ngữ → rút gọn: while + V-ing (while working).",
  },
  {
    id: "q15-079",
    difficulty: "medium",
    imageUrl: "/images/skills/writing-q1-5/q15-079.jpg",
    imageAlt: "Hai thợ máy mặc đồng phục xám cùng kiểm tra động cơ dưới nắp ca-pô xe đang mở.",
    keywords: ["hood", "under"],
    modelAnswers: ["Two mechanics are working under the hood of a car.", "The mechanics are checking the engine under the hood."],
    tip: "under the hood = dưới nắp ca-pô (Anh-Mỹ). Anh-Anh dùng under the bonnet.",
  },
];
